[package]
name = "changelog_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.3.11", features = ["derive"] }
pretty_assertions = "1.4.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
slug = "0.1.6"

[dev-dependencies]
assert_fs = "1.1.2"
mockall = "0.13.0"
rstest = "0.23.0"
