coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto

ignore:
  # Waiting for https://github.com/rust-lang/rust/issues/84605 resolution
  - "src/settings.rs"
  - "src/main.rs"

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
